creating pagination
alexandrryazanov/for-oleg-react pull request #3
Opened 2022-05-24 13:24 UTC by TheDezmant

2022-05-24 13:24 UTC, TheDezmant commented
[alexandrryazanov](https://github.com/alexandrryazanov) Hello

2022-05-24 13:27 UTC, alexandrryazanov approved these changes

2022-05-24 13:50 UTC, alexandrryazanov requested changes

2022-05-24 13:50 UTC, alexandrryazanov commented on src/Michael/components/Table/Dropdowns/LimitDropdown/LimitDropdown.tsx
> +  const limitItem = [2, 3, 5];
Заданная константа выносится из компонента и пишется в верхнем регистре

2022-05-24 13:50 UTC, alexandrryazanov commented on src/Michael/components/Table/Dropdowns/LimitDropdown/LimitDropdown.tsx
> +    <div className={"mwrapper_dropdown_limit"}>
Стили пишутся через дефис

2022-05-24 13:50 UTC, alexandrryazanov commented on src/Michael/components/Table/index.tsx
> +const dataCount = 10;
верхний регистр

2022-05-24 13:50 UTC, alexandrryazanov commented on src/Michael/components/Table/index.tsx
> +        <div className={"wrapper_mselect_amount_row"}>
везде поменяй названия короче

2022-05-24 13:50 UTC, alexandrryazanov commented on src/Michael/components/Table/index.tsx
> +          className={offset <= 0 ? "disable_mswitch-left" : "mswitch-left"}
тут вообще странное название, соединил 2 стиля написания

2022-05-24 13:50 UTC, alexandrryazanov commented on src/Michael/components/Table/style.css
> +    height: 92%;
используй calc

2022-05-24 13:50 UTC, alexandrryazanov commented on src/Michael/pages/Users/UsersTable/index.tsx
> +      setOffset={setOffset}
этим состоянием должна управлять только таблица

2022-05-24 13:50 UTC, alexandrryazanov commented on src/Michael/pages/Users/index.tsx
> +          limit={limit}
а где возмодность сделать таблицу без пагинации? Если тебе всегда приходят 2 строчки например. Зачем тебе вообще пагинация

2022-06-15 17:30 UTC, alexandrryazanov approved these changes

2022-06-15 17:30 UTC, merged